//
// About dialog for the Fast Light Tool Kit (FLTK).
//
// Copyright 1998-2021 by Bill Spitzak and others.
//
// This library is free software. Distribution and use rights are outlined in
// the file "COPYING" which should have been included with this file.  If this
// file is missing or damaged, see the license at:
//
//     https://www.fltk.org/COPYING.php
//
// Please see the following page on how to report bugs and issues:
//
//     https://www.fltk.org/bugs.php
//

// generated by Fast Light User Interface Designer (fluid) version 1.0400

#ifndef about_panel_h
#define about_panel_h
#include <FL/Fl.H>
#include "ui/panel.h"
#include <time.h>
extern void show_help(const char *name);
#include <FL/Fl_Double_Window.H>
#include "../src/flstring.h"
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Return_Button.H>
namespace fluid {
class Project;
namespace ui {

/**
 \brief Show some information about FLUID
*/
class AboutPanel : Panel {
  Fl_Double_Window* make_panel();
public:
  Fl_Double_Window *panel_window;
private:
  inline void cb_View_i(Fl_Button*, void*);
  static void cb_View(Fl_Button*, void*);
  inline void cb_Close_i(Fl_Return_Button*, void*);
  static void cb_Close(Fl_Return_Button*, void*);
public:
  AboutPanel();
  ~AboutPanel() override;
  void build() override;
  void show() override;
  void hide() override;
};
extern AboutPanel about_panel;
}
}
extern unsigned char fluid_flow_chart_800_png[41559];
#endif
