//
// Main Application Panel for the Fast Light Tool Kit (FLTK).
//
// Copyright 1998-2024 by Bill Spitzak and others.
//
// This library is free software. Distribution and use rights are outlined in
// the file "COPYING" which should have been included with this file.  If this
// file is missing or damaged, see the license at:
//
//     https://www.fltk.org/COPYING.php
//
// Please see the following page on how to report bugs and issues:
//
//     https://www.fltk.org/bugs.php
//

// generated by Fast Light User Interface Designer (fluid) version 1.0400

#ifndef main_panel_h
#define main_panel_h
#include <FL/Fl.H>
#include "ui/panel.h"
extern void show_help(const char *name);
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Menu_Bar.H>
extern void select_all_cb(Fl_Menu_*, void*);
extern void select_none_cb(Fl_Menu_*, void*);
extern void earlier_cb(Fl_Menu_*, void*);
extern void later_cb(Fl_Menu_*, void*);
extern void group_cb(Fl_Menu_*, void*);
extern void align_widget_cb(Fl_Menu_*, long);
extern void menu_layout_sync_resize_cb(Fl_Menu_*, void*);
#include "widget_browser.h"
namespace fluid {
class Project;
namespace ui {

/**
 \brief FLUID Main Application Panel
*/
class MainPanel : Panel {
  Fl_Double_Window* make_panel();
public:
  Fl_Double_Window *main_window;
private:
  inline void cb_main_window_i(Fl_Double_Window*, void*);
  static void cb_main_window(Fl_Double_Window*, void*);
public:
  Fl_Menu_Bar *main_menubar;
  static Fl_Menu_Item menu_main_menubar[];
private:
  inline void cb_New_i(Fl_Menu_*, void*);
  static void cb_New(Fl_Menu_*, void*);
  inline void cb_Open_i(Fl_Menu_*, void*);
  static void cb_Open(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *history_item;
private:
  inline void cb_history_item_i(Fl_Menu_*, void*);
  static void cb_history_item(Fl_Menu_*, void*);
  inline void cb__i(Fl_Menu_*, void*);
  static void cb_(Fl_Menu_*, void*);
  inline void cb_1_i(Fl_Menu_*, void*);
  static void cb_1(Fl_Menu_*, void*);
  inline void cb_2_i(Fl_Menu_*, void*);
  static void cb_2(Fl_Menu_*, void*);
  inline void cb_3_i(Fl_Menu_*, void*);
  static void cb_3(Fl_Menu_*, void*);
  inline void cb_4_i(Fl_Menu_*, void*);
  static void cb_4(Fl_Menu_*, void*);
  inline void cb_5_i(Fl_Menu_*, void*);
  static void cb_5(Fl_Menu_*, void*);
  inline void cb_6_i(Fl_Menu_*, void*);
  static void cb_6(Fl_Menu_*, void*);
  inline void cb_7_i(Fl_Menu_*, void*);
  static void cb_7(Fl_Menu_*, void*);
  inline void cb_8_i(Fl_Menu_*, void*);
  static void cb_8(Fl_Menu_*, void*);
  inline void cb_Insert_i(Fl_Menu_*, void*);
  static void cb_Insert(Fl_Menu_*, void*);
  inline void cb_Save_i(Fl_Menu_*, long);
  static void cb_Save(Fl_Menu_*, long);
  inline void cb_Save1_i(Fl_Menu_*, long);
  static void cb_Save1(Fl_Menu_*, long);
  inline void cb_Sa_i(Fl_Menu_*, long);
  static void cb_Sa(Fl_Menu_*, long);
  inline void cb_Revert_i(Fl_Menu_*, void*);
  static void cb_Revert(Fl_Menu_*, void*);
  inline void cb_New1_i(Fl_Menu_*, void*);
  static void cb_New1(Fl_Menu_*, void*);
  inline void cb_Save2_i(Fl_Menu_*, void*);
  static void cb_Save2(Fl_Menu_*, void*);
  inline void cb_Merge_i(Fl_Menu_*, void*);
  static void cb_Merge(Fl_Menu_*, void*);
  inline void cb_Write_i(Fl_Menu_*, void*);
  static void cb_Write(Fl_Menu_*, void*);
  inline void cb_Write1_i(Fl_Menu_*, void*);
  static void cb_Write1(Fl_Menu_*, void*);
  inline void cb_Print_i(Fl_Menu_*, void*);
  static void cb_Print(Fl_Menu_*, void*);
  inline void cb_Quit_i(Fl_Menu_*, void*);
  static void cb_Quit(Fl_Menu_*, void*);
  inline void cb_Undo_i(Fl_Menu_*, void*);
  static void cb_Undo(Fl_Menu_*, void*);
  inline void cb_Redo_i(Fl_Menu_*, void*);
  static void cb_Redo(Fl_Menu_*, void*);
  inline void cb_C_i(Fl_Menu_*, void*);
  static void cb_C(Fl_Menu_*, void*);
  inline void cb_Copy_i(Fl_Menu_*, void*);
  static void cb_Copy(Fl_Menu_*, void*);
  inline void cb_Paste_i(Fl_Menu_*, void*);
  static void cb_Paste(Fl_Menu_*, void*);
  inline void cb_Dupl_i(Fl_Menu_*, void*);
  static void cb_Dupl(Fl_Menu_*, void*);
  inline void cb_Delete_i(Fl_Menu_*, void*);
  static void cb_Delete(Fl_Menu_*, void*);
  inline void cb_Pr_i(Fl_Menu_*, void*);
  static void cb_Pr(Fl_Menu_*, void*);
  inline void cb_Sort_i(Fl_Menu_*, void*);
  static void cb_Sort(Fl_Menu_*, void*);
  inline void cb_Ung_i(Fl_Menu_*, void*);
  static void cb_Ung(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *overlay_item;
private:
  inline void cb_overlay_item_i(Fl_Menu_*, void*);
  static void cb_overlay_item(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *guides_item;
private:
  inline void cb_guides_item_i(Fl_Menu_*, void*);
  static void cb_guides_item(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *restricted_item;
private:
  inline void cb_restricted_item_i(Fl_Menu_*, void*);
  static void cb_restricted_item(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *widgetbin_item;
private:
  inline void cb_widgetbin_item_i(Fl_Menu_*, void*);
  static void cb_widgetbin_item(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *codeview_item;
private:
  inline void cb_codeview_item_i(Fl_Menu_*, void*);
  static void cb_codeview_item(Fl_Menu_*, void*);
  inline void cb_Settings_i(Fl_Menu_*, void*);
  static void cb_Settings(Fl_Menu_*, void*);
  inline void cb_Grid_i(Fl_Menu_*, void*);
  static void cb_Grid(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *suite_menu;
  static Fl_Menu_Item *preset_menu;
private:
  inline void cb_preset_menu_i(Fl_Menu_*, long);
  static void cb_preset_menu(Fl_Menu_*, long);
  inline void cb_Dialog_i(Fl_Menu_*, long);
  static void cb_Dialog(Fl_Menu_*, long);
  inline void cb_itemToolbox_i(Fl_Menu_*, long);
  static void cb_itemToolbox(Fl_Menu_*, long);
public:
  static Fl_Menu_Item *shell_submenu;
private:
  inline void cb_Rapid_i(Fl_Menu_*, void*);
  static void cb_Rapid(Fl_Menu_*, void*);
  inline void cb_FLTK_i(Fl_Menu_*, void*);
  static void cb_FLTK(Fl_Menu_*, void*);
  inline void cb_About_i(Fl_Menu_*, void*);
  static void cb_About(Fl_Menu_*, void*);
public:
  Widget_Browser *widget_browser;
  MainPanel();
  ~MainPanel() override;
  void build() override;
  void show() override;
  void hide() override;
};
extern MainPanel main_panel;
}
}
#endif
