//
// UI Panel Base Class for Fast Light User Interface Designer (FLUID).
//
// Copyright 1998-2024 by Bill Spitzak and others.
//
// This library is free software. Distribution and use rights are outlined in
// the file "COPYING" which should have been included with this file.  If this
// file is missing or damaged, see the license at:
//
//     https://www.fltk.org/COPYING.php
//
// Please see the following page on how to report bugs and issues:
//
//     https://www.fltk.org/bugs.php
//

// generated by Fast Light User Interface Designer (fluid) version 1.0400

#ifndef panel_h
#define panel_h
#include <FL/Fl.H>
namespace fluid {
namespace ui {
}
}
namespace fluid {
class Project;
namespace ui {

/**
 \brief Define a basic panel interface for all UI panels
*/
class Panel {
public:
  fluid::Project *project { nullptr };
  Panel();
  virtual ~Panel();
  virtual void build();
  virtual void show();
  virtual void hide();
  virtual void project_changed();
  virtual void selection_changed();
  void set_project(fluid::Project *p);
};
}
}
#endif
