//
// UI Panel Base Class for Fast Light User Interface Designer (FLUID).
//
// Copyright 1998-2024 by Bill Spitzak and others.
//
// This library is free software. Distribution and use rights are outlined in
// the file "COPYING" which should have been included with this file.  If this
// file is missing or damaged, see the license at:
//
//     https://www.fltk.org/COPYING.php
//
// Please see the following page on how to report bugs and issues:
//
//     https://www.fltk.org/bugs.php
//

// generated by Fast Light User Interface Designer (fluid) version 1.0400

#include "panel.h"
#include "project/project.h"
using namespace fluid::ui;

/**
 Constructor
*/
Panel::Panel() {
  // empty
}

/**
 Virtual destructor.
*/
Panel::~Panel() {
  // empty
}

/**
 Build the panel, don't show it yet.
*/
void Panel::build() {
  // empty
}

/**
 Build if needed and show the panel.
*/
void Panel::show() {
  // empty
}

/**
 Hide the panel and retain for later.
*/
void Panel::hide() {
  // empty
}

/**
 Call this when the project change or a different project is selected.
*/
void Panel::project_changed() {
  // empty
}

/**
 Call this if the type selection changed.
*/
void Panel::selection_changed() {
  // empty
}

/**
 Associate the panel with a project and refresh.
*/
void Panel::set_project(fluid::Project *p) {
  project = p;
  project_changed();
}
