//
// FLUID template support for the Fast Light Tool Kit (FLTK).
//
// Copyright 1998-2020 by Bill Spitzak and others.
//
// This library is free software. Distribution and use rights are outlined in
// the file "COPYING" which should have been included with this file.  If this
// file is missing or damaged, see the license at:
//
//     https://www.fltk.org/COPYING.php
//
// Please see the following page on how to report bugs and issues:
//
//     https://www.fltk.org/bugs.php
//

// generated by Fast Light User Interface Designer (fluid) version 1.0400

#ifndef template_panel_h
#define template_panel_h
#include <FL/Fl.H>
#include "ui/panel.h"
extern void show_help(const char *name);
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Browser.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Return_Button.H>
namespace fluid {
class Project;
namespace ui {

class TemplatePanel : public Panel {
  Fl_Double_Window* make_panel();
public:
  Fl_Double_Window *panel_window;
private:
  inline void cb_panel_window_i(Fl_Double_Window*, void*);
  static void cb_panel_window(Fl_Double_Window*, void*);
public:
  Fl_Browser *template_browser;
private:
  inline void cb_template_browser_i(Fl_Browser*, void*);
  static void cb_template_browser(Fl_Browser*, void*);
public:
  Fl_Box *template_preview;
  Fl_Input *template_name;
private:
  inline void cb_template_name_i(Fl_Input*, void*);
  static void cb_template_name(Fl_Input*, void*);
public:
  Fl_Input *template_instance;
  Fl_Button *template_delete;
private:
  inline void cb_template_delete_i(Fl_Button*, void*);
  static void cb_template_delete(Fl_Button*, void*);
  inline void cb_Cancel_i(Fl_Button*, void*);
  static void cb_Cancel(Fl_Button*, void*);
public:
  Fl_Return_Button *template_submit;
private:
  inline void cb_template_submit_i(Fl_Return_Button*, void*);
  static void cb_template_submit(Fl_Return_Button*, void*);
public:
  TemplatePanel();
  ~TemplatePanel() override;
  void build() override;
  void show() override;
  void hide() override;
  void template_clear();
  void template_install(const char *path, const char *name, const uchar *inSrc, int inSrcLen, int inDstLen);
  void template_load();
  void add(fluid::Project *project);
  bool load_template();
};
extern TemplatePanel template_panel;
}
}
#endif
